myapp/main/default/objects/datasheet__c/datasheet__c.object-meta.xml
<CustomObject>
    <description>This is for data sheet</description>
    <label>datasheet</label>
    <nameField>
        <label>datasheet Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

myapp/main/default/objects/datasheet__c/fields/property__c.field-meta.xml
<CustomField>
    <fullName>property__c</fullName>
    <label>erProperty</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>oneCheck</fullName>
            </value>
            <value>
                <fullName>twoCheck</fullName>
            </value>
            <value>
                <fullName>threeCheck</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

myapp/main/default/objects/surveyDataSheets__c/fields/investigatorQualificationErLevel__c.field-meta.xml
<CustomField>
    <fullName>investigatorQualificationErLevel__c</fullName>
    <label>investigatorQualificationErLevel</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>１級</fullName>
            </value>
            <value>
                <fullName>2級</fullName>
            </value>
            <value>
                <fullName>技士補</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

myapp/main/default/objects/surveyDataSheets__c/fields/investigatorQualificationMeasurement__c.field-meta.xml
<CustomField>
    <fullName>investigatorQualificationMeasurement__c</fullName>
    <label>investigatorQualificationMeasurement</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>測量士</fullName>
            </value>
            <value>
                <fullName>測量士補</fullName>
            </value>
            <value>
                <fullName>社内認定</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

myapp/main/default/classes/GetCheckboxValue.cls
public class GetCheckboxValue {
    @AuraEnabled(cacheable=true)
    public static List<String> getPicklistValues() {
        List<String> options = new List<String>();
        Schema.DescribeFieldResult fieldResult01 = surveyDataSheets__c.investigatorQualificationErLevel__c.getDescribe();
        List<Schema.PicklistEntry> pickListEntry01 = fieldResult01.getPicklistValues();

        for (Schema.PicklistEntry entry : pickListEntry01) {
            options.add(entry.getLabel());
        }
        return options;
    }
    @AuraEnabled(cacheable=true)
    public static List<String> getinvestigatorQualificationMeasurement() {
        List<String> options = new List<String>();
        Schema.DescribeFieldResult fieldResult01 = surveyDataSheets__c.investigatorQualificationMeasurement__c.getDescribe();
        List<Schema.PicklistEntry> pickListEntry01 = fieldResult01.getPicklistValues();

        for (Schema.PicklistEntry entry : pickListEntry01) {
            options.add(entry.getLabel());
        }
        return options;
    }
    @AuraEnabled(cacheable=true)
    public static list<String> getPreProcessCutMachineName(){
        List<String> options = new List<String>();
        Schema.DescribeFieldResult fieldResult01 = datasheet__c.pre_process_cutmachine_name__c.getDescribe();
        List<Schema.PicklistEntry> pickListEntry01 = fieldResult01.getPicklistValues();

        for (Schema.PicklistEntry entry : pickListEntry01) {
            options.add(entry.getLabel());
        }
        return options;
        
    }


    /*@AuraEnabled(cacheable = true)
    public static list<datasheet__c> getSoqlData(){
        list<datasheet__c> soqlData = new List<datasheet__c>();
        soqlData = [SELECT Name, property__c, pre_process_cutmchine_name__c, hidzuke__c
                    FROM datasheet__c
                    WHERE ];
    }*/
        //Create a variable for datasheet data to enter
        // datasheet__c ds = new datasheet__c();
        // public class Selection {
        //     public String label{get; set;}
        //     public String value{get; set;}
        //     public Boolean check{get; set;}
        //     public Selection(String label, String value, Boolean check) {
        //         this.label = label;
        //         this.value = value;
        //         this.check = check;
        //     }
        // } 
            //4. Investigator Qualification/Civil Engineering Construction management system - logged in Users -checkboxes /土木施工管理技士
            //public List<Selection> investigatorQualificationErLevel{get; set;}
    
            //5. Investigator Qualification/ Surveying Qualification - logged in Users /測量資格
           // public List<Selection> investigatorQualificationMeasurement{get; set;}

            // public getCheckboxValue(){
            //     this.propertyClassificationInput = new List<Selection>();
            //     this.investigatorQualificationErLevel = new List<Selection>();


            //     Schema.DescribeFieldResult fieldResult01 = surveyDataSheets__c.investigatorQualificationErLevel__c.getDescribe();
            //     List<Schema.PicklistEntry> pickListEntry01 = fieldResult01.getPicklistValues();
            //     for(integer i=0; i<pickListEntry01.size(); i++){
            //         System.debug('investigatorQualificationErLevel' + pickListEntry01[i].getValue());
            //         Selection selection = new Selection(pickListEntry01[i].getValue(), pickListEntry01[i].getLabel(),false);
            //         this.investigatorQualificationErLevel.add(selection); 
            //         }//end bracket of pickListEntry01
            // }

}